---
# tasks file for pca-gophish-composition
- name: Create the /var/pca/pca-gophish-composition directory
  file:
    path: /var/pca/pca-gophish-composition
    state: directory
    mode: 0755

- name: Download and untar the pca-gophish-composition tarball
  # ansible-lint E208 gives an error if we don't specify the mode, but
  # we definitely don't want to do that here since it will override
  # the permissions on the files in the archive.
  unarchive: # noqa 208
    src: >
      https://api.github.com/repos/cisagov/pca-gophish-composition/tarball/develop
    dest: /var/pca/pca-gophish-composition
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

# Install the pca-gophish-composition package in order to
# properly install the gophish_init script
- name: Install pca-gophish-composition via pip
  pip:
    chdir: /var/pca/pca-gophish-composition
    requirements: requirements.txt
    executable: pip3

- name: Install packages needed by gophish-tools helper scripts
  package:
    name:
      - at
      - jq
