---
- name: Create the /var/pca/pca-gophish-composition directory
  ansible.builtin.file:
    mode: 0755
    path: /var/pca/pca-gophish-composition
    state: directory

- name: Download and untar the pca-gophish-composition tarball
  ansible.builtin.unarchive:
    dest: /var/pca/pca-gophish-composition
    extra_opts:
      - "--strip-components=1"
    remote_src: yes
    src: https://api.github.com/repos/cisagov/pca-gophish-composition/tarball/develop

# Install the pca-gophish-composition package in order to properly
# install the gophish_init script
- name: Install pca-gophish-composition via pip
  ansible.builtin.pip:
    chdir: /var/pca/pca-gophish-composition
    executable: pip3
    # The extra argument is necessary on Debian 12, which correctly
    # recognizes that the local Python is externally managed
    # (i.e. managed via the system package manager and not by pip).
    # The extra argument is understood by pip on Debian and Kali
    # systems, but not others.
    extra_args: "{{ ansible_distribution is in ['Debian', 'Kali'] | ternary('--break-system-packages', omit) }}"
    requirements: requirements.txt

- name: Install packages needed by gophish-tools helper scripts
  ansible.builtin.package:
    name:
      - at
      - jq
