---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"

- name: Create the /var/pca/pca-gophish-composition directory
  ansible.builtin.file:
    mode: 0755
    path: /var/pca/pca-gophish-composition
    state: directory

- name: Install the tar package
  ansible.builtin.package:
    name:
     - tar

- name: Download and untar the pca-gophish-composition tarball
  ansible.builtin.unarchive:
    dest: /var/pca/pca-gophish-composition
    extra_opts:
      - "--strip-components=1"
    remote_src: yes
    src: https://api.github.com/repos/cisagov/pca-gophish-composition/tarball/develop

# Install the pca-gophish-composition package in order to properly
# install the gophish_init script
- name: Install pca-gophish-composition
  block:
    - name: Install prerequisites
      ansible.builtin.package:
        name: "{{ prerequisite_package_names }}"
    - name: Install pca-gophish-composition in a Python virtual environment
      ansible.builtin.pip:
        chdir: /var/pca/pca-gophish-composition
        requirements: requirements.txt
        virtualenv: /var/pca/pca-gophish-composition/.venv
