---
- name: Create the /var/pca/pca-gophish-composition directory
  ansible.builtin.file:
    mode: 0755
    path: /var/pca/pca-gophish-composition
    state: directory

- name: Install the tar package
  ansible.builtin.package:
    name:
     - tar

- name: Download and untar the pca-gophish-composition tarball
  ansible.builtin.unarchive:
    dest: /var/pca/pca-gophish-composition
    extra_opts:
      - "--strip-components=1"
    remote_src: yes
    src: https://api.github.com/repos/cisagov/pca-gophish-composition/tarball/develop

# Install the pca-gophish-composition package in order to properly
# install the gophish_init script
- name: Install pca-gophish-composition
  block:
    - name: Install prerequisites
      ansible.builtin.package:
        name:
          # at and jq are needed by the gophish-tools helper scripts
          - at
          - jq
          # virtualenv is used by the ansible.builtin.pip module below
          - virtualenv
    - name: Install pca-gophish-composition in a Python virtual environment
      ansible.builtin.pip:
        chdir: /var/pca/pca-gophish-composition
        requirements: requirements.txt
        virtualenv: /var/pca/pca-gophish-composition/.venv
