---
# tasks file for pca-gophish-composition
- name: Create the /var/pca/pca-gophish-composition directory
  file:
    path: /var/pca/pca-gophish-composition
    state: directory
    mode: 0755

- name: Download and untar the pca-gophish-composition tarball
  unarchive:
    src: >
      https://api.github.com/repos/cisagov/pca-gophish-composition/tarball/v0.0.3
    dest: /var/pca/pca-gophish-composition
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

# Install the pca-gophish-composition package in order to
# properly install the gophish_init script
- name: Install pca-gophish-composition via pip
  pip:
    chdir: /var/pca/pca-gophish-composition
    requirements: requirements.txt
    executable: pip3
